/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Course {
  'id' : string,
  'status' : string,
  'duration' : string,
  'name' : string,
  'level' : string,
  'enrollment' : bigint,
  'category' : string,
}
export interface Stats {
  'totalStudents' : bigint,
  'certifications' : bigint,
  'activeCourses' : bigint,
  'trainers' : bigint,
}
export interface _SERVICE {
  'getCourses' : ActorMethod<[], Array<Course>>,
  'getStats' : ActorMethod<[], Stats>,
  'login' : ActorMethod<
    [string, string],
    {
        'ok' : {
          'user' : { 'role' : string, 'email' : string },
          'sessionToken' : string,
        }
      } |
      { 'err' : string }
  >,
  'logout' : ActorMethod<[string], undefined>,
  'verifySession' : ActorMethod<
    [string],
    { 'ok' : { 'role' : string, 'email' : string } } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];