/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Course = IDL.Record({
  'id' : IDL.Text,
  'status' : IDL.Text,
  'duration' : IDL.Text,
  'name' : IDL.Text,
  'level' : IDL.Text,
  'enrollment' : IDL.Nat,
  'category' : IDL.Text,
});
export const Stats = IDL.Record({
  'totalStudents' : IDL.Nat,
  'certifications' : IDL.Nat,
  'activeCourses' : IDL.Nat,
  'trainers' : IDL.Nat,
});

export const idlService = IDL.Service({
  'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'login' : IDL.Func(
      [IDL.Text, IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({
            'user' : IDL.Record({ 'role' : IDL.Text, 'email' : IDL.Text }),
            'sessionToken' : IDL.Text,
          }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
  'logout' : IDL.Func([IDL.Text], [], []),
  'verifySession' : IDL.Func(
      [IDL.Text],
      [
        IDL.Variant({
          'ok' : IDL.Record({ 'role' : IDL.Text, 'email' : IDL.Text }),
          'err' : IDL.Text,
        }),
      ],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Course = IDL.Record({
    'id' : IDL.Text,
    'status' : IDL.Text,
    'duration' : IDL.Text,
    'name' : IDL.Text,
    'level' : IDL.Text,
    'enrollment' : IDL.Nat,
    'category' : IDL.Text,
  });
  const Stats = IDL.Record({
    'totalStudents' : IDL.Nat,
    'certifications' : IDL.Nat,
    'activeCourses' : IDL.Nat,
    'trainers' : IDL.Nat,
  });
  
  return IDL.Service({
    'getCourses' : IDL.Func([], [IDL.Vec(Course)], ['query']),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'login' : IDL.Func(
        [IDL.Text, IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({
              'user' : IDL.Record({ 'role' : IDL.Text, 'email' : IDL.Text }),
              'sessionToken' : IDL.Text,
            }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
    'logout' : IDL.Func([IDL.Text], [], []),
    'verifySession' : IDL.Func(
        [IDL.Text],
        [
          IDL.Variant({
            'ok' : IDL.Record({ 'role' : IDL.Text, 'email' : IDL.Text }),
            'err' : IDL.Text,
          }),
        ],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };